### ISSUE TITLE
react import error

### ISSUE THREAD

**Issue by whl5105** [wanted-pre-onboarding-internship-9/pre-onboarding-9th-2-9#9]

**Comment by yeon-kk** [comment]
https://ko.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html
React 17부터 import React는 필요하지 않기 때문에, ESLint에도 반영해야 하고 jsx-runtime 규칙을 추가해야 한다고 합니다.
그리고 airbnb 규칙 중 outdate된 내용이 있어서 eslintrc 파일의 extends에서 airbnb  규칙을 가장 상단으로 올리고 다른 규칙들이 이를 덮어쓰게 해야 합니다.
    "extends": [
        "airbnb",
        "airbnb-typescript",
        "airbnb/hooks",
        "eslint:recommended",
        "plugin:react/recommended",
        "plugin:react/jsx-runtime",
        "plugin:@typescript-eslint/recommended",
        "prettier"
    ],
